"""add role column with customer/seller check to users

Revision ID: 5a0ff94c3d33
Revises: eddbdd8512c4
Create Date: 2026-08-20 20:24:52.906472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ff94c3d33'
down_revision = 'eddbdd8512c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='customer', nullable=False))
        batch_op.create_check_constraint('users_role_check', "role IN ('customer', 'seller')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_role_check', type_='check')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
